---
title: "Plot power vs. fdr"
author: "Yunqi Yang"
date: "10/19/2022"
output: html_document
---

### Description: plot power vs. fdr by comparing lfsr with true means, varying training sample size. 

#### Simulating data parameter settings:
1. K = 5, Vj=I.
2. True Us: identity + 5 singletons. 

```{r include = FALSE}
knitr::opts_chunk$set(comment = "#",
                      results = "hold",
                      collapse = TRUE,
                      fig.align = "center",
                      warning = FALSE,
                      message = FALSE)
```


3. The scale of U, $s$ set to be 5.
4. R = 5, scale of U = 5
5. n.train = c(50, 100, 500, 2e3)
6. 50 data replicates


```{r}
# Create a data frame used to plot a power vs. FDR curve. Input
# argument "true" is a logical vector in which true[i] is TRUE if and
# only if the ith element is a true discovery; input argument "pval"
# may be either a vector of p-values of the same length as "true", or
# an equivalent ranking in which the discoveries with the strongest
# support are ordered first in an ordering obtained from order(pval).
# The output is a data frame with three columns: "power", "fdr" (false
# discovery rate") and "t", the latter being the threshold used to
# calculate power and FDR. Note power = TP/(TP + TN) and fdr = FP/(TP
# + FP), where TP is the number of true positives, FP is the number of
# false positives, and TN is the number of true negatives. The number
# of rows should be equal to either length.out or the number of unique
# p-values, whichever is smaller.
create_fdr_vs_power_curve <- function (pval, true, length.out = 200) {
  pval[is.na(pval)] <- max(pval,na.rm = TRUE)
  t <- unique(pval)
  if (length.out < length(t))
    t <- quantile(t,seq(0,1,length.out = length.out))
  else
    t <- sort(t)
  n   <- length(t)
  out <- data.frame(t = t,power = 0,fdr = 0)
  for (i in 1:n) {
    pos <- pval <= t[i]
    tp  <- sum(pos & true)
    fp  <- sum(pos & !true)
    fn  <- sum(!pos & true)
    out[i,"power"] <- tp/(tp + fn)
    out[i,"fdr"]   <- fp/(tp + fp)
  }
  return(out)
}
```


```{r}
source("./code/simulation_func.R")
library(udr)
library(mashr)
library(mvtnorm)
library(LaplacesDemon)
```

```{r}
K = 10
R = 5
s = 5
n.train = c(50, 100, 500, 2e3)
param = list(w = rep(1/K, K), U = list(), V = diag(R))
seeds = c(1:50)

```

```{r cache = TRUE}

output.oracle <- list()
for (i in 1:length(n.train)){
  theta_mat = list()
  lfsr_mat = list()
  for (seed in seeds){
      set.seed(seed)
      param$U <-  sim_U_true(R, s, null.mat = FALSE, identity = TRUE, num_singleton = 5, num_unconstrained = 4)
      dat.train <- simulate_mixture_ebnm(n.train[i], param$w,param$U,param$V)
      mc <- mash_set_data(dat.train$X, Shat = 1)
      
      theta_mat[[seed]] = dat.train$theta
      
      g.fitted <- create_g(param$w, param$U)
      res <- mash(mc, g = g.fitted, fixg = TRUE)
      lfsr_mat[[seed]] <- res$result$lfsr
    }
  output.oracle[[i]] <- create_fdr_vs_power_curve(unlist(lfsr_mat), unlist(theta_mat), length.out = 50)
}

```


#### Use ED algorithm to fit. 
```{r cache = TRUE}

output.ed1 <- list()
for (i in 1:length(n.train)){
  theta_mat = list()
  lfsr_mat = list()
  for (seed in seeds){
      set.seed(seed)
      param$U <-  sim_U_true(R, s, null.mat = FALSE, identity = TRUE, num_singleton = 5, num_unconstrained = 4)
      dat.train <- simulate_mixture_ebnm(n.train[i], param$w,param$U,param$V)
      mc <- mash_set_data(dat.train$X, Shat = 1)
      
      theta_mat[[seed]] = dat.train$theta
      
      set.seed(888)
      U.init = c()
      for (k in 1:K){
        U.init[[k]] <- udr:::sim_unconstrained(R)
      }
      f0 = ud_init(X = dat.train$X, V = param$V, U_scaled = NULL, U_unconstrained = U.init, n_rank1 = 0)
      # Fit ED
      fit = ud_fit(f0, control = list(unconstrained.update = "ed", resid.update = 'none',
                                      tol = 1e-02, tol.lik = 1e-2, n0 = 0, lambda = 0, maxiter = 5e3), verbose=FALSE)
      U <- lapply(fit$U,function (e) "[["(e,"mat"))
      g.fitted <- create_g(fit$w, U)
      res <- mash(mc, g = g.fitted, fixg = TRUE)
      lfsr_mat[[seed]] <- res$result$lfsr
    }
  output.ed1[[i]] <- create_fdr_vs_power_curve(unlist(lfsr_mat), unlist(theta_mat), length.out = 50)
}

```

#### Use TED algorithm to fit. 
```{r cache = TRUE}

output.ted1 <- list()
for (i in 1:length(n.train)){
  theta_mat = list()
  lfsr_mat = list()
  for (seed in seeds){
      set.seed(seed)
      param$U <-  sim_U_true(R, s, null.mat = FALSE, identity = TRUE, num_singleton = 5, num_unconstrained = 4)
      dat.train <- simulate_mixture_ebnm(n.train[i], param$w,param$U,param$V)
      mc <- mash_set_data(dat.train$X, Shat = 1)
      
      theta_mat[[seed]] = dat.train$theta
      
      set.seed(888)
      U.init = c()
      for (k in 1:K){
        U.init[[k]] <- udr:::sim_unconstrained(R)
      }
      f0 = ud_init(X = dat.train$X, V = param$V, U_scaled = NULL, U_unconstrained = U.init, n_rank1 = 0)
      # Fit ED
      fit = ud_fit(f0, control = list(unconstrained.update = "ted", resid.update = 'none',
                                      tol = 1e-02, tol.lik = 1e-2, n0 = 0, lambda = 0, maxiter = 5e3), verbose=FALSE)
      U <- lapply(fit$U,function (e) "[["(e,"mat"))
      g.fitted <- create_g(fit$w, U)
      res <- mash(mc, g = g.fitted, fixg = TRUE)
      lfsr_mat[[seed]] <- res$result$lfsr
    }
  output.ted1[[i]] <- create_fdr_vs_power_curve(unlist(lfsr_mat), unlist(theta_mat), length.out = 50)
}

```

```{r}

plot(output.ed1[[1]]$fdr, output.ed1[[1]]$power, col = 1, type = "b",  pch = 20, cex = 0.5,
     ylab = "power", xlab = "fdr", main = "ED fit")
points(output.ed1[[2]]$fdr, output.ed1[[2]]$power, col = 2, type = "b", pch = 20, cex = 0.5)
points(output.ed1[[3]]$fdr, output.ed1[[3]]$power, col = 3, type = "b", pch = 20, cex = 0.5)
points(output.ed1[[4]]$fdr, output.ed1[[4]]$power, col = 4, type = "b", pch = 20, cex = 0.5)
legend("topleft", legend = c("n: 50", "n: 100", "n: 500", "n: 2e3"), 
       col = c(1:4), lty=1)


plot(output.ted1[[1]]$fdr, output.ted1[[1]]$power, col = 1, type = "b",  pch = 20, cex = 0.5,
     ylab = "power", xlab = "fdr", main = "TED fit")
points(output.ted1[[2]]$fdr, output.ted1[[2]]$power, col = 2, type = "b", pch = 20, cex = 0.5)
points(output.ted1[[3]]$fdr, output.ted1[[3]]$power, col = 3, type = "b", pch = 20, cex = 0.5)
points(output.ted1[[4]]$fdr, output.ted1[[4]]$power, col = 4, type = "b", pch = 20, cex = 0.5)
legend("topleft", legend = c("n: 50", "n: 100", "n: 500", "n: 2e3"), 
       col = c(1:4), lty=1)
```

```{r}
par(mfrow = c(2,2))

for (i in 1:4){
  main = paste0("Compare with oracle: n = ", n.train[i])
  plot(output.oracle[[i]]$fdr, output.oracle[[i]]$power, col = 1, type = "b",  pch = 20, cex = 0.5,
     ylab = "power", xlab = "fdr", main = main)
points(output.ed1[[i]]$fdr, output.ed1[[i]]$power, col = 2, type = "b",  pch = 20, cex = 0.5)
points(output.ted1[[i]]$fdr, output.ted1[[i]]$power, col = 3, type = "b",  pch = 20, cex = 0.5)
legend("topleft", legend = c("oracle", "ed", "ted"), col = c(1:3), lty=1, cex = 0.6)
}

```

